### ISSUE TITLE
Création du footer

### ISSUE THREAD

**Issue by nygmasx** [nygmasx/SchoolIndex#2]
### Création du Footer (c'est le même partout) et l'implémenter sur toutes les pages

Dans ce footer il doit y avoir trois liens dans lequel il y a des points entre les éléments.
Les liens sont les suivants :

- Mentions légales
- Contact
- Lycée Saint-Vincent

Voici ce a quoi devrait ressembler le footer : 

![image](https://github.com/nygmasx/SchoolIndex/assets/126764347/901827b4-2ce0-40c0-9e87-105bda234b38)

**Comment by nourdyne** [comment]
Dans ce footer il doit y avoir trois liens dans lequel il y a des points entre les éléments.
Les liens sont les suivants : 
- Mentions légales
- Contact
- Lycée Saint-Vincent
